apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    uid: P8E80F9AEF21F6940
    isDefault: false
    editable: true
    jsonData:
      derivedFields:
        - datasourceUid: jaeger
          matcherRegex: '"trace_id"\\s*:\\s*"([a-f0-9]{32})"'
          name: TraceID
          url: ${__value.raw}
        - datasourceUid: jaeger
          matcherRegex: '"traceId"\\s*:\\s*"([a-f0-9]{32})"'
          name: TraceID (camelCase)
          url: ${__value.raw}
        - datasourceUid: jaeger
          matcherRegex: 'trace_id=([a-f0-9]{32})'
          name: TraceID (Text)
          url: ${__value.raw}
